version: "2.1"

services:
  app:
    # Replace 0.1.0 with the exact Ocean Palette release version to run.
    image: baealex/ocean-palette:0.1.0
    ports:
      - 7768:7768
    volumes:
      - ./data:/data
      - ./assets:/assets
