ALTER TABLE "Keyword" ADD COLUMN "meaning" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Keyword" ADD COLUMN "effect" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Keyword" ADD COLUMN "note" TEXT NOT NULL DEFAULT '';
